Slimmmo/Slimmmo.github.io

- index.html
- js/main.js
Changed the recommendation equation based on Dash2in1's comment at https://www.reddit.com/r/AdventureCapitalist/comments/3ik18l/another_calculator/
Looked good to me and I wanted to use it myself, so I changed it.
> New recommendation equation

- js/main.js
"hh:mm:ss" time formatting, showing days if necessary
> Improved time formatting

- js/main.js
I missed changing some upgrade score calculation, so the "top recommendation" gave the wrong value, though the table was correct.
> fixed top recommendation bug

- js/main.js
No longer ends up in an infinite loop, as it previously did with a value of "input" = "Infinity" in the numFilter function. Also attempts to fix display upon a value of "Infinity" (so it doesn't display as "Infinity d" or something).
Unfortunately doesn't fix the value displayed in the "% Increase in $ / Second" column.
> Fix looping when $/second is 0

- index.html
- js/main.js
Some angel upgrades are only worth like 11% gain, others are 500%. 
This just shares the % in the tooltip on the ! mark for now.  
(Ignore that upgrades look completely different, that is not in this PR)
> Angel upgrades indicate the % increase they provide

- js/main.js
Load on pageload / save on calculate.
> Save to local storage

- index.html
- js/main.js
- Added Select All button for Mega Tickets, and Managers
- Added "Hard Reset" Button which acts as the old reset function, now a Reset just clears things you lose while claiming angel investers (cash upgrades, angel upgrades, and investments). Mega Tickets, Angels, Triples, etc. are kept.
> Select All Button & Soft/Hard Reset

- js/main.js
I don't know if this is backwards compatible. If you know it will break loading suggest a way for me to fix it and I will add that in. I have a feeling if noSingles and noTens isn't saved it won't load properly but I am unsure. I attempted to save the time filters however couldn't get it to work correctly so perhaps you could add that in at some point. This at least keeps the Don't show +1 and Don't show +10 upon reloading.
> Save (some) filters

- index.html
- js/main.js
Add ability to hide mega ticket column on planets that don't have them.
> Hide mega tickets on event

- css/bonusstyle.css
- index.html
- js/main.js
Just like what happens with suits, you can now see the best badge to wear on the current planet
> Showing suggestion of best badge to wear on planet

- js/main.js
As mentioned in #80, I made a function to show the stored amount of angels in a more readable format, as {quantity} {order of magnitude}, like _"7.8 septillion"_ instead of _7800000000000000000000000_.
> Loading gamestate now shows numAngels in a more readable format

- parseGameState.py
Python was throwing errors because the spacing (which indicates identation on Python) was incorrect.
> parseGameState - Fixed spacing

- js/main.js
Added this event's super badge, 'Time Machine'.
> Excellent - Super Badge

- js/main.js
This PR gets rid of the extra row that shows up in the "Cost of Upgrades" table.
> Fix extra row displaying in the "Cost of Upgrades" table.

- js/main.js
Add "Budget Light" Super Badge; correct "basePower" for Million Dollar Dip
> Corrections for Profit-A-Bowl

- js/main.js
Changed "Foam Sitff-arms" to "Foam Stiff-arms"; put "Hypno-ads" and "Designer Uniforms" in correct order
> Correct investment list for Profit-A-Bowl

- js/main.js
Adds support for Teal Suit -- "Wear it on any/all planets to add +30% Angel Effectiveness" costs 1500 Mega Bucks. (I can't figure out if there's a way to test proposed code changes before submitting them, so please check to see if the changes make sense.)
> Add support for Teal Suit

- js/main.js
The March, 2018, replay of "Insert Coins to Continue" includes "gilding"
> Add "MegaTickets" to Insert Coins to Continue

- js/main.js
Current (April, 2018) Replay of Saturday Morning Fever allows "Gilding" investments
> Add 'Gilding' to Saturday Morning Fever

- js/main.js
Reverts Slimmmo/Slimmmo.github.io#184 Made a typo
> Revert "Adds "gilding" to Gates of Heck"

- js/main.js
Latest version of Gates of Heck allows gilding investments; this adds that ability to the calculator
> Adds "gilding" to Gates of Heck

- js/main.js
Adds the new Cashalot Event from March, 2019
> Add Cashalot Event
